name: node install
inputs:
  node-version:
    type: string
    default: 16.x
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ inputs.node-version }}
