name: runme install
inputs:
  go-version:
    type: string
    default: '1.19'
    required: true
  version:
    type: string
    default: v0.6.5
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ inputs.go-version }}

    - name: Install runme
      shell: bash
      run: go install github.com/stateful/runme@${{ inputs.version }}
