name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup runme
      uses: vrunoa/github-actions/runme@base-actions

    - name: Setup node
      uses: vrunoa/github-actions/node@base-actions

    - run: runme run install-deps
    - run: runme run lint
    - run: runme run unit:test
